SELECT P.PRODUCT_ID ,ROUND(IFNULL( SUM(p.price * u.units) / SUM(u.units),0),2) AS AVERAGE_PRICE
FROM PRICES AS P
LEFT JOIN UNITSSOLD AS U
ON P.PRODUCT_ID = U.PRODUCT_ID
 AND U.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE
 GROUP BY P.PRODUCT_ID;
